### ISSUE TITLE
Support `--only` and `--without` for `poetry lock`

### ISSUE THREAD

**Issue by WillDaSilva** [idantene/poet-exclusive-groups-plugin#2]
Thank you for making this plugin. It work as described, and is useful. Unfortunately I do not believe I can use this because the following dependency structure results in an error when running `poetry lock`:

```toml
[tool.poetry.group.prod.dependencies]
foo = {git = "https://github.com/bar/foo", subdirectory = "src/libs/foo"}

[tool.poetry.group.dev.dependencies]
foo = {path = "../../libs/foo", develop = true}
```

Error:

```
Because poet-test-project depends on both foo (1.2.3) @ git+https://github.com/bar/foo#subdirectory=src/libs/foo and foo (1.2.3) @ file:///home/will/workshop/poet-test-project/src/libs/foo, version solving failed.
```

Is there some way to use the sort of dependency structure proposed by this plugin with `poetry lock`? I think it might make sense to support the `--only` and `--without` CLI options for `poetry lock` so that the lockfile can ignore one of the two versions of the dependency.
